namespace=WWMIv1


; SHAPE KEYS API -------------------------

; Sets value of custom Shape Key or override value of original one
[CommandListSetShapeKey]
; Usage example (set value override for Shape Key 86 to 0.5):
; $shapekeys_update_required = 1
; $\WWMIv1\shapekey_id = 86
; $\WWMIv1\shapekey_value = 0.5
; cs-u5 = ResourceCustomShapeKeyValuesRW
; run = CommandList\WWMIv1\SetShapeKey
;
; Input:
; $\WWMIv1\shapekey_id (int, range [0, 127])
; $\WWMIv1\shapekey_value (float, range [0.0, 1.0])
; cs-u5 = ResourceCustomShapeKeyValuesRW
$shapekey_mode = 0
run = CustomShaderShapeKeySetter


; Disables value override of original Shape Key
[CommandListDisableShapeKeyOverride]
; Usage example (disable value override for Shape Key 21):
; $shapekeys_update_required = 1
; $\WWMIv1\shapekey_id = 21
; cs-u5 = ResourceCustomShapeKeyValuesRW
; run = CommandList\WWMIv1\DisableShapeKeyOverride
;
; Input:
; $\WWMIv1\shapekey_id (int, range [0, 127])
; cs-u5 = ResourceCustomShapeKeyValuesRW
$shapekey_mode = 1
run = CustomShaderShapeKeySetter


; TEXT PRINTER API -------------------------

; Prints text on screen using provided params
[CommandListPrintText]
; Input:
; Resource\WWMIv1\Text
; Resource\WWMIv1\TextParams
;
; Usage example (resource formats are listed below):
; Resource\WWMIv1\Text = ref ResourceMyText
; Resource\WWMIv1\TextParams = ref ResourceMyTextParams
; run = CommandList\WWMIv1\PrintText
run = CommandListRenderText


; Text string example resource printable by CommandListPrintText
[ResourceTextExample]
type = Buffer
data = "Hello World!"


; Text file example resource printable by CommandListPrintText
[ResourceTextFileExample]
type = buffer
format = R8_UINT
filename = MyText.txt


; Text params example resource for CommandListPrintText
; Using these parameter buffers as a way to pass in constant parameters without
; taking up any of the IniParams slots while still allowing the parameters to
; be customised on a per-message basis.
[ResourceTextParamsExample]
type = StructuredBuffer
array = 1
data = R32_FLOAT  -0.25 +0.15 +0.25 -0.05   1.00 1.00 1.00 1.00   0.00 0.00 0.00 0.95   0.02  0.05   2 1   1   1.0
;                x1-^  y1-^  x2-^  y2-^   | R-^  G-^  B-^  A-^  | R-^  G-^  B-^  A-^  | ^-H    V-^ | ^ ^ | ^- text alignment: 0=left 1=center 2=right | ^- font scale
;                Rectangle (range -1:+1)  | Text Color          | Background Color    | Border     |  ^- h/v-anchor: 0=none 1=left/top 2=center 3=right/bottom 
