namespace=WWMIv1


; Constants -------------------------

[Constants]

global $shapekey_vertex_count = 0
global $shapekey_checksum = 0

global $shapekey_checksum_batch0 = 0
global $shapekey_vertex_offset_original_batch0 = 0
global $shapekey_vertex_offset_custom_batch0 = 0
global $shapekey_checksum_batch1 = 0
global $shapekey_vertex_offset_original_batch1 = 0
global $shapekey_vertex_offset_custom_batch1 = 0

global $shapekey_vertex_count_batch0 = 0
global $shapekey_dispatch_size_y_original_batch0 = 0
global $shapekey_vertex_count_batch1 = 0
global $shapekey_dispatch_size_y_original_batch1 = 0

global $shapekey_mode = 0
global $shapekey_id = 0
global $shapekey_value = 0


; Hooks -------------------------

; Overides original Shape Key Loader CS call
[ShaderOverrideShapeKeyLoaderCS]
hash = 9bf4420c82102011
allow_duplicate_hash = true
filter_index = 3381.3333
; Fire callbacks for mods that are listening on cs-u0 slot (shape key data)
if $enable_mods
    if cs-u0 >= 1
        checktextureoverride = cs-u0
    endif
endif


; Overides original Shape Key Multiplier CS call
[ShaderOverrideShapeKeyMultiplierCS]
hash = 7a8396180d416117
allow_duplicate_hash = true
filter_index = 3381.4444
; Fire callbacks for mods that are listening on cs-u0 slot (shape key data)
if $enable_mods
    if cs-u0 >= 1
        checktextureoverride = cs-u0
    endif
endif


; Shape Keys Shaders -------------------------

; Writes custom shape key values to provided RWBuffer
[CustomShaderShapeKeySetter]
; Load shader and explicitly unbind other shaders for safety
cs = Shaders/SkapeKeySetter.hlsl
vs = null
ps = null
hs = null
ds = null
gs = null
; Backup used IniParams
local $bak_x0 = x0
local $bak_y0 = y0
local $bak_z0 = z0
; Pass variables to the shader
x0 = $shapekey_mode
y0 = $shapekey_id
z0 = $shapekey_value
; Pass resources to the shader
; cs-u5 = ResourceCustomShapeKeyValuesRW
; cs-u7 = ResourceDebugRW
; Run the compute shader
dispatch = 1, 1, 1
; Unbind resources
cs-u5 = null
; Restore IniParams:
post x0 = $bak_x0
post y0 = $bak_y0
post z0 = $bak_z0


; Updates provided RWBuffer that stores offsets of shapekeyed vertex lists, shape key values and multipliers
[CustomShaderShapeKeyOverrider]
; Load shader and explicitly unbind other shaders for safety
cs = Shaders/ShapeKeyOverrider.hlsl
vs = null
ps = null
hs = null
ds = null
gs = null
; Backup used IniParams
local $bak_x0 = x0
local $bak_y0 = y0
local $bak_z0 = z0
local $bak_x1 = x1
local $bak_y1 = y1
local $bak_z1 = z1
; Pass variables to the shader
; Inputs:
; $\WWMIv1\shapekey_checksum = 1415
; Batch 0
x0 = $shapekey_checksum
y0 = 0
z0 = 0
; Batch 1
x1 = 0
y1 = 0
z1 = 0
; Pass resources to the shader
; Inputs:
; cs-t33 = ResourceShapeKeyOffsetBuffer
; cs-u5 = ResourceCustomShapeKeyValuesRW
; cs-u6 = ResourceShapeKeyCBRW
; cs-u7 = ResourceDebugRW
; Run the compute shader
Dispatch = 1, 1, 1
; Unbind resources
cs-t33 = null
cs-u5 = null
cs-u6 = null
; Restore IniParams:
post x0 = $bak_x0
post y0 = $bak_y0
post z0 = $bak_z0
post x1 = $bak_x1
post y1 = $bak_y1
post z1 = $bak_z1


; Updates provided RWBuffer that stores offsets of shapekeyed vertex lists, shape key values and multipliers
[CustomShaderShapeKeyBatchOverrider]
; Load shader and explicitly unbind other shaders for safety
cs = Shaders/ShapeKeyOverrider.hlsl
vs = null
ps = null
hs = null
ds = null
gs = null
; Backup used IniParams
local $bak_x0 = x0
local $bak_y0 = y0
local $bak_z0 = z0
local $bak_x1 = x1
local $bak_y1 = y1
local $bak_z1 = z1
; Pass variables to the shader
; Inputs:
; $\WWMIv1\shapekey_checksum_batch0 = 1415
; $\WWMIv1\shapekey_vertex_offset_original_batch0 = 0
; $\WWMIv1\shapekey_vertex_offset_custom_batch0 = 0
; $\WWMIv1\shapekey_checksum_batch1 = 1560
; $\WWMIv1\shapekey_vertex_offset_original_batch1 = 50426
; $\WWMIv1\shapekey_vertex_offset_custom_batch1 = 50560
; Batch 0
x0 = $shapekey_checksum_batch0
y0 = $shapekey_vertex_offset_original_batch0
z0 = $shapekey_vertex_offset_custom_batch0
; Batch 1
x1 = $shapekey_checksum_batch1
y1 = $shapekey_vertex_offset_original_batch1
z1 = $shapekey_vertex_offset_custom_batch1
; Pass resources to the shader
; Inputs:
; cs-t33 = ResourceShapeKeyOffsetBuffer
; cs-u5 = ResourceCustomShapeKeyValuesRW
; cs-u6 = ResourceShapeKeyCBRW
; cs-u7 = ResourceDebugRW
; Run the compute shader
Dispatch = 1, 1, 1
; Unbind resources
cs-t33 = null
cs-u5 = null
cs-u6 = null
; Restore IniParams:
post x0 = $bak_x0
post y0 = $bak_y0
post z0 = $bak_z0
post x1 = $bak_x1
post y1 = $bak_y1
post z1 = $bak_z1


; Loads xyz offsets for each vertex and global shape key multiplier to xyz offsets
[CustomShaderShapeKeyLoader]
; Load shader and explicitly unbind other shaders for safety
cs = Shaders/ShapeKeyLoader.hlsl
vs = null
ps = null
hs = null
ds = null
gs = null
; Pass variables to the shader
; Inputs:
; $\WWMIv1\shapekey_vertex_count = $shapekey_vertex_count
; Pass resources to the shader
; Inputs:
; cs-t0 = ResourceShapeKeyVertexIdBuffer
; cs-t1 = ResourceShapeKeyVertexOffsetBuffer
; cs-u6 = ResourceShapeKeyCBRW
; cs-u7 = ResourceDebugRW
; Run the compute shader
local $dispatch_y = $shapekey_vertex_count/32+1
if $dispatch_y < THREAD_GROUP_COUNT_Y
    $dispatch_y = THREAD_GROUP_COUNT_Y
endif
dispatch = 1, $dispatch_y, 1
; Unbind resources
cs-u6 = null


; Selects appropriate $shapekey_vertex_count for current shapekeys batch and calls CustomShaderShapeKeyLoader
[CommandListLoadShapeKeysBatch]
if THREAD_GROUP_COUNT_Y == $shapekey_dispatch_size_y_original_batch0
    $shapekey_vertex_count = $shapekey_vertex_count_batch0
elif THREAD_GROUP_COUNT_Y == $shapekey_dispatch_size_y_original_batch1
    $shapekey_vertex_count = $shapekey_vertex_count_batch1
else
    ; THREAD_GROUP_COUNT_Y based detection failed (most likely due to original mesh update).
    ; Fallback to the size of the largest batch.
    ; Dispatching more threads than needed won't hurt, but it'll waste a bit of performance.
    if $shapekey_dispatch_size_y_original_batch0 > $shapekey_dispatch_size_y_original_batch1
        $shapekey_vertex_count = $shapekey_dispatch_size_y_original_batch0
    else
        $shapekey_vertex_count = $shapekey_dispatch_size_y_original_batch1
    endif
endif
run = CustomShaderShapeKeyLoader


; Applies dynamic unique per-character shape key multiplier to xyz offsets 
[CustomShaderShapeKeyMultiplier]
; Load shader and explicitly unbind other shaders for safety
cs = Shaders/ShapeKeyMultiplier.hlsl
vs = null
ps = null
hs = null
ds = null
gs = null
; Pass variables to the shader
; Inputs:
; $\WWMIv1\shapekey_vertex_count = $shapekey_vertex_count
; Pass resources to the shader
; cs-u7 = ResourceDebugRW
; Run the compute shader
local $dispatch_y = $custom_vertex_count/32+1
if $dispatch_y < THREAD_GROUP_COUNT_Y
    $dispatch_y = THREAD_GROUP_COUNT_Y
endif
dispatch = 1, $dispatch_y, 1


; Applies shape key xyz offsets to position buffer data
[CustomShaderShapeKeyApplier]
; Load shader and explicitly unbind other shaders for safety
cs = Shaders/ShapeKeyApplier.hlsl
vs = null
ps = null
hs = null
ds = null
gs = null
; Backup used IniParams
local $bak_x0 = x0
local $bak_y0 = y0
; Pass variables
x0 = $custom_vertex_offset
y0 = $custom_vertex_count
; Pass variables to the shader
; Inputs:
; $\WWMIv1\shapekey_vertex_count = $shapekey_vertex_count
; Pass resources to the shader
; cs-u6 = PositionDataRW
; cs-u7 = ResourceDebugRW
; Run the compute shader
dispatch = $custom_vertex_count/64+1, 1, 1
; Unbind resources
cs-u6 = null
; Restore IniParams:
post x0 = $bak_x0
post y0 = $bak_y0
