namespace=WWMIv1


; Includes -------------------------

[IncludeTextPrinter]
include = TextPrinter.ini

[IncludeShapeKeysEngine]
include = ShapeKeys.ini

[Include KeyBindings]
include = KeyBindings.ini

[IncludeUtilities]
include = WWMI-Utilities.ini

[IncludeLegacyTextPrinter]
include = help.ini

[IncludeAPI]
include = API.ini


; Resources -------------------------

[ResourceModName]
[ResourceModAuthor]
[ResourceModDesc]
[ResourceModLink]
[ResourceModLogo]

[ResourceDebugRW]
type = RWBuffer
format = R32G32B32A32_FLOAT
array = 128

[ResourceVersionNotification]
type = Buffer
data = "WWMI 1.1.0 (PRESS F12 TO SHOW GUIDE)"


; Constants -------------------------

[Constants]

global $wwmi_version = 1.10

global $enable_ib_callbacks = 0

global $enable_mods = 1

global persist $first_run = 1
global $show_compatibility_mode_notification = 0
global $compatibility_mode_switch_time = 0
global $show_user_guide = 0
global $show_hunting_mode_guide = 0
global $mods_display_switch_time = 0

global $object_guid = 0
global $mod_id = 0
global $required_wwmi_version = 0

global $vg_offset = 0
global $vg_count = 0

global $custom_vertex_offset = 0
global $custom_vertex_count = 0
global $custom_mesh_scale = 1.0

global $blend_remap_id = 0
global $weights_per_vertex_count = 0
global $blend_remap_bone_count = 512

; Deprecated
global $window_width = 3840
global $window_height = 1600
global persist $enable_compatibility_mode = 0
global $enable_vb0_callbacks = 1
global $component_draw_calls_count = 25


; Present -------------------------

[Present]
; pre Resource\Debugger\DebugRW = copy ResourceDebugRW
run = CommandListRenderGUI


; Core Logic -------------------------

[CommandListToggleMods]
$enable_mods = !$enable_mods
$mods_display_switch_time = time


[CommandListToggleCompatibilityMode]
$enable_compatibility_mode = !$enable_compatibility_mode
$compatibility_mode_switch_time = time


[CommandListHideNotification]
ResourceErrorIncompatibleVersionModNameRef = null


; Registers mod in WWMI and returns $mod_id
; If returned $mod_id == -1, mod must disable all its functions for user safety
[CommandListRegisterMod]
; Dummy method to handle registration
; TODO: Make proper registration system
$mod_id = 1
; Ensure that user had required version of WWMI
if $wwmi_version < $required_wwmi_version
    ResourceErrorIncompatibleVersionRef = ref ResourceErrorOldVersionWWMI
    $mod_id = -1
endif
; Ensure that mod uses supported version of installed WWMI API
if $required_wwmi_version < 0.6
    ResourceErrorIncompatibleVersionRef = ref ResourceErrorOldVersionMod
    $mod_id = -1
; Ensure that mod uses supported version of installed WWMI API
elif $required_wwmi_version < 0.7 && !$enable_compatibility_mode
    ResourceErrorIncompatibleVersionRef = ref ResourceErrorCompatibilityModeDisabled
    $mod_id = -1
endif
; Set mod name for error display if there is version incompatibility
if $mod_id == -1
    if ResourceModName === null
        ResourceModName = ResourceUnnamedModName
    endif
    ResourceErrorIncompatibleVersionModNameRef = copy ResourceModName
endif


; Hooks -------------------------

; Fires callbacks for mods that are listening on vb0 slot (draw calls)
[CommandListFireCallbacks]
CheckTextureOverride = vb0
if $enable_ib_callbacks
    CheckTextureOverride = ib
endif
if $enable_compatibility_mode
    CheckTextureOverride = vs-cb3
    CheckTextureOverride = vs-cb4
endif


; Hooks to ALL vertex shaders to track required resource updates
[ShaderRegexEnableTextureOverrides]
shader_model = vs_4_0 vs_4_1 vs_5_0 vs_5_1
if $enable_mods
    run = CommandListFireCallbacks
endif


; Skeleton Override -------------------------

; Merges bone data from provided buffer into provided merged skeleton buffer
[CustomShaderSkeletonMerger]
; Load shader and explicitly unbind other shaders for safety
cs = Shaders/SkeletonMerger.hlsl
vs = null
ps = null
hs = null
ds = null
gs = null
; Backup used IniParams
local $bak_x1 = x1
local $bak_z1 = z1
local $bak_w1 = w1
; Pass variables
x1 = $custom_mesh_scale
z1 = $vg_offset
w1 = $vg_count
; Pass resources to the shader
; Expects cs-cb0
; Expects bone data resource in cs-t3 or cs-t4
; Expects merged skeleton resource in cs-u6
; cs-u6 = ResourceMergedSkeletonRW
; cs-u7 = ResourceDebugRW
; Run the compute shader
dispatch = $vg_count/64+1, 1, 1
; Unbind resources
cs-u6 = null
; Restore IniParams:
post x1 = $bak_x1
post z1 = $bak_z1
post w1 = $bak_w1


; Dummy shader to supress errors
[CustomShaderMeshSkinner]
cs = null
vs = null
ps = null
hs = null
ds = null
gs = null


; Remaps VG ids in Blend.buf copy according to "reverse" VG map (OG -> Mapped)
[CustomShaderBlendRemapper]
; Load shader and explicitly unbind other shaders for safety
cs = Shaders/BlendRemapper.hlsl
vs = null
ps = null
hs = null
ds = null
gs = null
; Backup used IniParams
local $bak_y0 = y0
local $bak_x2 = x2
local $bak_y2 = y2
; Pass variables
y0 = $custom_vertex_count
x2 = $blend_remap_id
y2 = $weights_per_vertex_count
w2 = $blend_remap_bone_count
; Pass resources to the shader
; Input Resources:
; cs-t34 - "reverse" VG map (i.e. {51:0, 286:1} map transforms [12, 286, 51] to [12, 1, 0])
; cs-t35 - array of blendicies, required since OG Blend.buf stores VG ids as 8-bit UINTs, while we need 16-bit at least
; Output Resources:
; cs-u4 - remapped blend buffer 
; cs-u7 = ResourceDebugRW
; Run the compute shader
dispatch = $custom_vertex_count/64+1, 1, 1
; Reset variables
$blend_remap_bone_count = 512
; Unbind resources
cs-u4 = null
; Restore IniParams:
post y0 = $bak_y0
post x2 = $bak_x2
post y2 = $bak_y2


; Remaps VG ids in merged skeleton buffer copy according to "forward" VG map (Mapped -> OG)
[CustomShaderSkeletonRemapper]
; Load shader and explicitly unbind other shaders for safety
cs = Shaders/SkeletonRemapper.hlsl
vs = null
ps = null
hs = null
ds = null
gs = null
; Backup used IniParams
local $bak_w1 = w1
local $bak_x2 = x2
; Pass variables
w1 = $vg_count
x2 = $blend_remap_id
w2 = $blend_remap_bone_count
; Pass resources to the shader
; Input Resources:
; cs-t37 - "forward" VG map (i.e. {0:0, 1:2} map transforms [VG0_DATA, VG1_DATA, VG2_DATA] to [VG0_DATA, VG2_DATA])
; cs-t38 - merged skeleton
; Output Resources:
; cs-u5 - remapped merged skeleton 
; cs-u7 = ResourceDebugRW
; Reset variables
$blend_remap_bone_count = 512
; Run the compute shader
dispatch = $vg_count/64+1, 1, 1
; Unbind resources
cs-u5 = null
; Restore IniParams:
post w1 = $bak_w1
post x2 = $bak_x2


; GUI -------------------------

[CommandListRenderGUI]

if time < 30
    ResourceText = ref ResourceVersionNotification
    ResourceTextParams = ref ResourceVersionNotificationParams
    run = CommandListPrintText
    if $first_run
        $show_user_guide = 1
    endif
endif

if $show_user_guide
    ResourceText = ref ResourceUserGuide
    ResourceTextParams = ref ResourceUserGuideParams
    run = CommandListPrintText
elif $show_hunting_mode_guide
    ResourceText = ref ResourceHuntingModeGuide
    ResourceTextParams = ref ResourceUserGuideParams
    run = CommandListPrintText
endif

if $mods_display_switch_time != 0
    if $enable_mods
        ResourceText = ref ResourceModsDisplayEnabled
    else
        ResourceText = ref ResourceModsDisplayDisabled
    endif
    ResourceTextParams = ResourceTopNotificationParams
    run = CommandListPrintText
    if time - $mods_display_switch_time > 1.5
        $mods_display_switch_time = 0
    endif
endif

if ResourceErrorIncompatibleVersionModNameRef !== null
    ResourceText = ref ResourceErrorIncompatibleVersionRef
    ResourceTextParams = ref ResourceUserNotificationParams
    run = CommandListPrintText

    ResourceText = ref ResourceErrorIncompatibleVersionModNameRef
    ResourceTextParams = ref ResourceErrorIncompatibleVersionModNameParams
    run = CommandListPrintText
endif

if $compatibility_mode_switch_time != 0
    if $enable_compatibility_mode
        ResourceText = ref ResourceCompatibilityModeEnabled
    else
        ResourceText = ref ResourceCompatibilityModeDisabled
    endif
    ResourceTextParams = ResourceTopNotificationParams
    run = CommandListPrintText
    if time - $compatibility_mode_switch_time > 3
        $compatibility_mode_switch_time = 0
    endif
endif


; GUI Resources -------------------------

[ResourceModsDisplayEnabled]
type = Buffer
data = "Mods Display: Enabled"


[ResourceModsDisplayDisabled]
type = Buffer
data = "Mods Display: Disabled"


[ResourceCompatibilityModeEnabled]
type = Buffer
data = "Compatibility Mode: Enabled"


[ResourceCompatibilityModeDisabled]
type = Buffer
data = "Compatibility Mode: Disabled"


[ResourceUserGuide]
type = buffer
format = R8_UINT
filename = Notifications/UserGuide.md


[ResourceHuntingModeGuide]
type = buffer
format = R8_UINT
filename = Notifications/HuntingModeGuide.md


[ResourceErrorOldVersionMod]
type = buffer
format = R8_UINT
filename = Notifications/ErrorOldVersionMod.md


[ResourceErrorCompatibilityModeDisabled]
type = buffer
format = R8_UINT
filename = Notifications/ErrorCompatibilityModeDisabled.md


[ResourceErrorOldVersionWWMI]
type = buffer
format = R8_UINT
filename = Notifications/ErrorOldVersionWWMI.md


[ResourceErrorIncompatibleVersionRef]
[ResourceErrorIncompatibleVersionModNameRef]


[ResourceUnnamedModName]
type = Buffer
data = "< Unnamed Mod >"


[ResourceTopNotificationParams]
type = StructuredBuffer
array = 1
data = R32_FLOAT  -0.25 +0.90 +0.25 +0.80   1.00 1.00 1.00 1.00   0.00 0.00 0.00 0.80   0.02  0.03   2 1   1   1.0
;                x1-^  y1-^  x2-^  y2-^   | R-^  G-^  B-^  A-^  | R-^  G-^  B-^  A-^  | ^-H    V-^ | ^ ^ | ^- text alignment: 0=left 1=center 2=right | ^- font scale
;                Rectangle (range -1:+1)  | Text Color          | Background Color    | Border     |  ^- h/v-anchor: 0=none 1=left/top 2=center 3=right/bottom 


[ResourceUserNotificationParams]
type = StructuredBuffer
array = 1
data = R32_FLOAT  -0.25 +0.15 +0.25 -0.05   1.00 1.00 1.00 1.00   0.00 0.00 0.00 0.80   0.02  0.05   2 1   1   1.0
;                x1-^  y1-^  x2-^  y2-^   | R-^  G-^  B-^  A-^  | R-^  G-^  B-^  A-^  | ^-H    V-^ | ^ ^ | ^- text alignment: 0=left 1=center 2=right | ^- font scale
;                Rectangle (range -1:+1)  | Text Color          | Background Color    | Border     |  ^- h/v-anchor: 0=none 1=left/top 2=center 3=right/bottom 

[ResourceErrorIncompatibleVersionModNameParams]
type = StructuredBuffer
array = 1
data = R32_FLOAT  -0.25 +0.15 +0.25 -0.05   1.00 1.00 1.00 1.00   0.00 0.00 0.00 0.00   0.02  0.05   2 1   1   1.0
;                x1-^  y1-^  x2-^  y2-^   | R-^  G-^  B-^  A-^  | R-^  G-^  B-^  A-^  | ^-H    V-^ | ^ ^ | ^- text alignment: 0=left 1=center 2=right | ^- font scale
;                Rectangle (range -1:+1)  | Text Color          | Background Color    | Border     |  ^- h/v-anchor: 0=none 1=left/top 2=center 3=right/bottom 


[ResourceVersionNotificationParams]
type = StructuredBuffer
array = 1
data = R32_FLOAT  -0.95 -0.90 -0.00 -0.85   1.00 1.00 1.00 1.00   0.00 0.00 0.00 0.00   0.02  0.05   1 1   1   1.0
;                x1-^  y1-^  x2-^  y2-^   | R-^  G-^  B-^  A-^  | R-^  G-^  B-^  A-^  | ^-H    V-^ | ^ ^ | ^- text alignment: 0=left 1=center 2=right | ^- font scale
;                Rectangle (range -1:+1)  | Text Color          | Background Color    | Border     |  ^- h/v-anchor: 0=none 1=left/top 2=center 3=right/bottom 


[ResourceUserGuideParams]
type = StructuredBuffer
array = 1
data = R32_FLOAT  -0.40 +0.00 +0.40 -0.00   1.00 1.00 1.00 1.00   0.00 0.00 0.00 0.80   0.02  0.05   2 2   0   1.0
;                x1-^  y1-^  x2-^  y2-^   | R-^  G-^  B-^  A-^  | R-^  G-^  B-^  A-^  | ^-H    V-^ | ^ ^ | ^- text alignment: 0=left 1=center 2=right | ^- font scale
;                Rectangle (range -1:+1)  | Text Color          | Background Color    | Border     |  ^- h/v-anchor: 0=none 1=left/top 2=center 3=right/bottom 

; EoF -------------------------
